### ISSUE TITLE
bios要怎么设置呢？

### ISSUE THREAD

**Issue by zzyandzzy** [CasperNan/opencore-ASUS-B460m-plus-10400#1]
安装的时候直接禁行了。主板一样，10400无独显。

**Comment by CasperNan** [comment]
你可以参考一下这个 [Opencore官方推荐bios设置](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#intel-bios-settings)

**Comment by CasperNan** [comment]
> 你可以参考一下这个 [Opencore官方推荐bios设置](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#intel-bios-settings)

具体在conifg ->comet lake->intel bios settings
