### ISSUE TITLE
大佬问一下我这个配置可以直接用你的配置文件吗？

### ISSUE THREAD

**Issue by RayJiang16** [CasperNan/opencore-ASUS-B460m-plus-10400#2]
ASUS TUF GAMING B460M Pro
I5 10400F
RX590

另外再问下注意事项2里的需要下载Resource文件夹生成图形启动是什么意思，下载Resource文件夹后要放到EFI里面吗？

**Comment by CasperNan** [comment]
可以直接用 不过config文件里面的那个SMBIOS要自己用GenSMBIOS生成 具体信息在[这里](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#platforminfo)
那个Resource下载到OC文件夹下即可 详细信息可以看这里 [图形启动的添加](https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-opencore-s-gui)
